locale                   : "en-US"
title                    : "Vikas Chandrashekar"
title_separator          : "-"
name                     : &name "Vikas Chandrashekar"
description              : &description "Software Engineer."
theme                    : jekyll-theme-minimal
