locale                   : "en-US"
title                    : "Hello World!"
title_separator          : "-"
name                     : &name "Vikas Chandrashekar"
description              : &description "Software Engineer & Consultant"
theme                    : jekyll-theme-minimal
