locale                   : "en-US"
title                    : "Vikas Chandrashekar"
# Build settings
markdown                 : kramdown
remote_theme             : VikasChandrashekar/jekyll-theme-console

# page settings
footer                   : '<a href = "mailto: vikas.chandrashekar@outlook.com">email</a> 
                            <a href = "https://github.com/VikasChandrashekar">github</a>
                            <a href = "">resume</a>'
header_pages             :
  - index.md
